anonticket/urls.py
from django.urls import path, include, reverse
from django.views.generic import (
    TemplateView, DetailView, ListView, CreateView, UpdateView)
from . import views
from django.conf import settings
from anonticket.views import (
    CreateIdentifierView, 
    IssueSuccessView,
    ObjectCreatedNoUserView,
    UserLoginErrorView,
    GitlabAccountRequestCreateView,
    CannotCreateObjectView,
    ProjectListView,
    ProjectDetailView,
    PendingIssueDetailView,
    NoteCreateView,
    ModeratorNoteUpdateView,
    ModeratorIssueUpdateView,
    ModeratorGitlabAccountRequestUpdateView,
    )


urlpatterns = [
    path(
        '', 
        TemplateView.as_view(template_name="anonticket/index.html"), 
        name='home'),
    path(
        'user/create_identifier/', 
        views.CreateIdentifierView.as_view(), 
        name='create-identifier'),
    path(
        'user/login/', 
        views.login_view, name='login'),
    path(
        'user/gitlab-account/create/', 
        views.GitlabAccountRequestCreateView.as_view(), 
        name='create-gitlab-no-user'),
    path(
        'user/<str:user_identifier>/create-failed/', 
        views.CannotCreateObjectView.as_view(), 
        name='cannot-create-with-user'),
    path(
        'user/<str:user_identifier>/gitlab-account/create/', 
        views.GitlabAccountRequestCreateView.as_view(), 
        name='create-gitlab-with-user'),
    path(
        'user/<str:user_identifier>/login_error/', 
        views.UserLoginErrorView.as_view(), name='user-login-error'),
    path(
        'user/<str:user_identifier>/projects/<slug:project>/issues/<int:issue_iid>/notes/create/', 
        views.NoteCreateView.as_view(), 
        name='create-note'),
    path(
        'user/<str:user_identifier>/projects/<slug:project>/issues/<int:issue_iid>/notes/<int:pk>/', 
        views.PendingNoteDetailView.as_view(), name='pending-note'),
    path(
        'user/<str:user_identifier>/projects/<slug:project_slug>/issues/<int:gitlab_iid>/details/', 
        views.issue_detail_view, name='issue-detail-view'),
    path(
        'user/<str:user_identifier>/projects/<slug:project_slug>/issues/pending/<int:pk>/', 
        views.PendingIssueDetailView.as_view(), name='pending-issue-detail-view'),
    path(
        'user/<str:user_identifier>/projects/all/issues/search/', 
        views.issue_search_view, name="issue-search"),
    path(
        'user/<str:user_identifier>/projects/<slug:slug>/', 
        views.ProjectDetailView.as_view(), name='project-detail'),
    path(
        'user/<str:user_identifier>/projects/', 
        views.ProjectListView.as_view(), name='project-list'),
    path(
        'user/<str:user_identifier>/create/success/', 
        views.IssueSuccessView.as_view(), name='issue-created'),
    path(
        'user/create/success/', 
        views.ObjectCreatedNoUserView.as_view(), name='created-no-user'),         
    path(
        'user/<str:user_identifier>/create_issue/', 
        views.create_issue_view, name='create-issue'),
    path(
        'user/<str:user_identifier>/', 
        views.user_landing_view, name='user-landing'),
    path(
        'moderator/', 
        views.moderator_view, name='moderator'),
    path(
        'moderator/update-note/<int:pk>', 
        views.ModeratorNoteUpdateView.as_view(), 
        name='mod-update-note'),
    path(
        'moderator/update-issue/<int:pk>', 
        views.ModeratorIssueUpdateView.as_view(), 
        name='mod-update-issue'),
    path(
        'moderator/update-gitlab-account-request/<int:pk>', 
        views.ModeratorGitlabAccountRequestUpdateView.as_view(), 
        name='mod-update-gitlab-account-request'),
]

ticketlobby/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tor_admin/', admin.site.urls),
    path('', include('anonticket.urls'))
]

anonticket/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django import forms
import gitlab

# Create your models here.

class UserIdentifier(models.Model):
    """Representation of a user identifier."""
    user_identifier = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True, blank=False)

    def __str__(self):
        return self.user_identifier

class Project(models.Model):
    """Representation of a project in the database. To add a GL project 
    to the database, only the gitlab id number needs to be supplied in the
    gitlab_id field. Upon saving, the project details and any necessary
    group details will be fetched from gitlab."""
    gitlab_id = models.IntegerField(help_text="""IMPORTANT: Enter a 
    gitlab ID into this field and save, and the project's details will 
    be fetched from gitlab! NOTHING ELSE ON THIS FORM NEEDS TO BE 
    FILLED IN. Additionally, if a project is saved, a fresh copy of
    the gitlab details will be fetched and the database entries will
    be updated.""")
    name = models.CharField(max_length=200, null=True, blank=True)
    name_with_namespace = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    slug = models.SlugField(max_length=50, null=True, blank=True)
    url = models.URLField(null=True, blank=True)

    def fetch_from_gitlab(self):
        """Given the gitlab_id, fetch the relevant information from Gitlab."""
        # Create the gitlab object
        gl = gitlab.Gitlab(settings.GITLAB_URL, private_token=settings.GITLAB_SECRET_TOKEN)
        # Grab the associated project from gitlab.
        try: 
            working_project = gl.projects.get(self.gitlab_id)
            self.name = working_project.name
            self.name_with_namespace = working_project.name_with_namespace
            self.description = working_project.description 
            self.slug = slugify(working_project.name)
            self.url = working_project.web_url
        # if the project does not have a gitlab_group foreignkey, first
        # check to see if a GitLabGroup object with the gitlab id exists.
        except:
            pass

    def save(self, *args, **kwargs):
        """Update the save method to fetch fresh info from gitlab when projects are saved."""
        self.fetch_from_gitlab()
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.name_with_namespace

class Issue(models.Model):
    """A representation of a user reported issue."""
    title = models.CharField(max_length=200)
    linked_project = models.ForeignKey(Project, on_delete=models.CASCADE)
    linked_user = models.ForeignKey(UserIdentifier, on_delete=models.CASCADE)
    description= models.TextField()
    gitlab_iid = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=False)
    mod_comment = models.TextField(
        blank=True, 
        verbose_name='Moderator Comment', 
        help_text="""As a moderator, you can add a comment to this item. 
        Once saved, it will appear on the moderator landing page and can
        be seen by all moderators, but it will not be seen by users. """,
    )
    
    # The following fields related to reviewer status:
    # Django recommends defining choice_list outside of CharField.
    REVIEWER_STATUS_CHOICES = [
        ('P', 'Pending Review'),
        ('A', 'Approved'),
        ('R', 'Rejected'),
    ]
    # Reviewer 
    reviewer_status = models.CharField(
        max_length=3,
        choices=REVIEWER_STATUS_CHOICES,
        default='P',  
    )
    # Fields related to GitLab status
    posted_to_GitLab = models.BooleanField(default=False)

    def approve_issue(self):
        """Approve an issue and post to GitLab or return error."""
        # Create the gitlab object
        gl = gitlab.Gitlab(settings.GITLAB_URL, private_token=settings.GITLAB_SECRET_TOKEN)
        # Grab the associated project from gitlab.
        working_project = gl.projects.get(self.linked_project.gitlab_id)
        # Try to create the issue in the gitlab API, saving the newly
        # created issue iid to the model's issue.iid field.
        try:
            new_issue = working_project.issues.create(
                {'title': self.title,
                'description': self.description}
                )
            self.posted_to_GitLab = True
            self.gitlab_iid = new_issue.iid
        except:
            pass

    def save(self, *args, **kwargs):
        if self.reviewer_status == 'A' and self.gitlab_iid == None:
            self.approve_issue() 
        super(Issue, self).save(*args, **kwargs) 

    def __str__(self):
        return self.title

class Note(models.Model):
    """A representation of a note to be created for an issue. """
    # Require a Foreign-Key relationship with a Project object, as notes
    # should only be created for Projects in the database.
    linked_project = models.ForeignKey(Project, on_delete=models.CASCADE)
    linked_user = models.ForeignKey(
        UserIdentifier, on_delete=models.CASCADE)
    # This is the note/comment body.
    body = models.TextField(
        verbose_name='Note Contents',
        help_text="""Type your note body here. You 
            can use <a href='https://docs.gitlab.com/ee/user/markdown.html'
            target="_blank">
            GitLab Flavored Markdown (GFM)</a> on this form.""")
    # issue_iid is not a ForeignKey because Issue objects in database
    # are for issues pending mod approval.
    issue_iid = models.IntegerField()
    # Allow note_id field to be blank as this will be pulled from gitlab.
    # gitlab_issue_title = models.CharField(blank=True, max_length=200, null=True)
    gitlab_id = models.IntegerField(blank=True, null=True)
    gitlab_issue_title = models.CharField(blank=True, max_length=200)
    created_at = models.DateTimeField(auto_now_add=True, blank=False)
    mod_comment = models.TextField(
        blank=True, 
        verbose_name='Moderator Comment', 
        help_text="""As a moderator, you can add a comment to this item. 
        Once saved, it will appear on the moderator landing page and can
        be seen by all moderators, but it will not be seen by users. """,
    )

    # The following fields related to reviewer status:
    # Django recommends defining choice_list outside of CharField.
    REVIEWER_STATUS_CHOICES = [
        ('P', 'Pending Review'),
        ('A', 'Approved'),
        ('R', 'Rejected'),
    ]
    # Reviewer 
    reviewer_status = models.CharField(
        max_length=3,
        choices=REVIEWER_STATUS_CHOICES,
        default='P',  
    )
    # Fields related to GitLab status
    posted_to_GitLab = models.BooleanField(default=False)

    def approve_note(self):
        """Approve a note and post to GitLab or return error."""
        # Create the gitlab object
        gl = gitlab.Gitlab(settings.GITLAB_URL, private_token=settings.GITLAB_SECRET_TOKEN)
        # Grab the associated project from gitlab.
        working_project = gl.projects.get(self.linked_project.gitlab_id)
        # Grab the associated issue from gitlab.
        working_issue = working_project.issues.get(self.issue_iid)
        # Try to create the note in the gitlab API, saving the newly
        # created note id to the note.gitlab_id field.
        try:
            new_note = working_issue.notes.create(
                {'body': self.body,
                }
                )
            self.posted_to_GitLab = True
            self.gitlab_id = new_note.id
        except:
            pass

    def get_issue_title(self):
        """Returns the title of the issue from GitLab."""
        gl = gitlab.Gitlab(settings.GITLAB_URL, private_token=settings.GITLAB_SECRET_TOKEN)
        working_project = gl.projects.get(self.linked_project.gitlab_id)
        working_issue = working_project.issues.get(self.issue_iid)
        return working_issue.title

    def save(self, *args, **kwargs):
        if not self.gitlab_issue_title:
            self.gitlab_issue_title = self.get_issue_title()
        if self.reviewer_status == 'A' and self.gitlab_id == None:
            self.approve_note() 
        super(Note, self).save(*args, **kwargs) 

    def __str__(self):
        return self.body

#Define a custom validator for the GitLab Account Request that checks
# if the username already exists in Gitlab.

def check_if_user_in_gitlab(username_to_test):
    """Validator to check if a username already exists in GitLab."""
    # Create the gitlab object using the ACCOUNTS token
    gl = gitlab.Gitlab(
        settings.GITLAB_URL, 
        private_token=settings.GITLAB_ACCOUNTS_SECRET_TOKEN
        )
    try: 
        user = gl.users.list(username=f"{username_to_test}")[0]
        raise ValidationError(
            _('%(username_to_test)s is already taken.'),
            params={'username_to_test': username_to_test},
        )
    #An IndexError means the username was not found.
    except IndexError:
        pass

class GitlabAccountRequest(models.Model):
    """A model of a user's request to create a GitLab account."""
    # SlugField chosen over CharField due to Gitlab's restrictions
    # on usernames.
    username = models.SlugField(
        max_length=64, 
        unique=True, 
        help_text= """Type your requested username here. Note that your 
        username MUST start with a letter or number, and that usernames
        can only use letters (A-Z, a-z), numbers, underscores (_), and 
        hyphens(-).""",
        validators=[check_if_user_in_gitlab]
        )
    email = models.EmailField()
    reason = models.CharField(
        max_length=256, 
        help_text = """Please explain why you want to collaborate with the 
        Tor Community.""",
    )
    REVIEWER_STATUS_CHOICES = [
        ('P', 'Pending Review'),

anonticket/templates/anonticket/base_template.html
<!-- Extend the layout template -->
<!-- Can leave any of these as default -->
{% extends 'shared/layout.html' %}
<!-- Load static method for templates -->
{% load static %}
<!-- title block sets the main title on the page (in browser bar)-->
{% block title %}
  Anon Ticket
{% endblock %}
<!-- extra_links block allows for additional menu items -->
{% block extra_links %}
{% endblock %}
<!-- h3 block sets the main title -->
{% block h3 %}
  Anon Ticket
{% endblock %}
<!-- Subheader block sets the subheader -->
{% block subheader %} 
  Anonymous Ticket Reporting for GitLab
{% endblock %}
<!-- block content block is where page contents go -->
{% block content %}
{% endblock %}

anonticket/templates/anonticket/create_identifier.html
{% extends 'shared/layout.html' %}
{% load static %}
{% block h3 %}
  Anon-Ticket
{% endblock %}
{% block subheader %} 
  Generate Anonymous Identifier
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-11 pr-5">
      <p class="pr-5"> Anon-Ticket identifiers are code-phrases consisting of
        six words randomly chosen from a dictionary.</p>
      <p class="pr-5"> A user identifier has been generated for you below. 
        If you don't like this identifier, you 
        can <a href="{% url 'create-identifier' %}">reload the page</a>,
      and another one will be generated for you.</p>
      <p>When you have a code-phrase you like, make sure to save it somewhere. 
         A lost code-phrase <mark>cannot be looked up.</mark></p>
    </div>
  </div>
  <div class="row justify-content-center bg-light p-1 mt-3 mb-3 ml-3 mr-3 col-10">
    {% for word in chosen_words %}
      <div class="col-auto p-2 mb-2">
        <h4 class="text-primary">{{word}}</h4>
      </div>
    {% endfor %}
  </div>
  <div class="row justify-content-start mb-3 col-10">
    <form action="{% url 'create-identifier' %}" class="col-sm-auto mt-2">
      <button type="submit" class="btn btn-lg btn-primary mr-2">
        Choose a Different Identifier
      </button>
    </form>
    <!-- Generate the user_login_link on the fly -->
    {% url 'user-landing' user_identifier_string as login_url %}
    <form action="{{login_url}}" class="col-sm-auto mt-2 ml-2">
      <button type="submit" class="btn btn-lg btn-primary mr-2">
        Login With This Identifier
      </button>
    </form>
  </div>
{% endblock %}

anonticket/templates/anonticket/create_issue_success.html
<!-- Extend the layout template -->
<!-- Can leave any of these as default -->
{% extends 'shared/layout.html' %}
<!-- Load static method for templates -->
{% load static %}
<!-- title block sets the main title on the page (in browser bar)-->
{% block title %}
  Anon Ticket
{% endblock %}
<!-- h3 block sets the main title -->
{% block h3 %}
  Anon Ticket
{% endblock %}
<!-- Subheader block sets the subheader -->
{% block subheader %} 
  Your issue, note, or request has been saved and is pending moderator approval.
{% endblock %}
<!-- Extra links block for pages that have a user_identifier piped to them.-->
{% block extra_links %}
  {% include 'shared/extend_sidebar.html' %}
{% endblock %}
<!-- block content block is where page contents go -->
{% block content %}
{% if results.user_identifier %}
<div class="row">
  <div class="col-12">
    {% url 'user-landing' results.user_identifier as go_back_url %}
  <p>
    <a href="{{go_back_url}}">Back to my landing page</a>
  </p>
  </div>
</div>
{% else %}
<div class="row">
  <div class="col-12">
    <p>
      <a href="{% url 'home' %}">Return to Home Page</a>
    </p>
  </div>
</div>
{% endif %}
{% endblock %}

anonticket/templates/anonticket/create_new_issue.html
{% extends 'shared/layout.html' %}
{% load static %}
{% block h3 %}
  Anon Ticket
{% endblock %}
{% block subheader %} 
  Create an Issue Report and Save it To the Database
{% endblock %}
<!-- Extra links block for pages that have a user_identifier piped to them.-->
{% block extra_links %}
  {% include 'shared/extend_sidebar.html' %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-12">
    <p class="p-3">
      This form will allow you to create an issue/ticket for 
      a specific project. Please note that not all of TorProject's GitLab 
      repos are currently using this anonymous portal--so if you 
      don't find the project in the dropdown below, you will not be
      able to create a ticket for it using this system.
    </p>
    <p class="p-3">
      All issues are held in a pending status until they're approved by
      a moderator. You can check the status of your issue at any time
      on 
      {% url 'user-landing' results.user_identifier as landing_url %}
      <a href="{{landing_url}}">your landing page</a>.
    </p>
    <p class="p-3">
      Before creating a new issue report, please try 
      {% url 'issue-search' results.user_identifier as issue_url %}
      <a href="{{issue_url}}">searching the for the issue</a> 
      first, to avoid duplication.
    </p>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <form class="bg-light p-4 form-control ml-3 mr-3" method="POST">
      {% csrf_token %}
      <!--Loop over form fields, allowing for custom styling. Help-text 
      and custom labels/descriptions are taken from forms.py-->
      {% for field in form %}
        <div class="fieldWrapper form-group">
          {{ field.errors }}
          
          <div class="row">
            <div class="col-12">
              <div class="mb-0">{{ field.label_tag }}</div>
            </div>
          </div>

          {% if field.help_text %}
          <div class="row">
            <div class="col-12">
              <div class="help small p-0 text-muted mb-2">
                {{ field.help_text|safe }}
              </div>
            </div>
          </div>
          {% endif %}

          <div class="row">
            <div class="col-12">
              <div class="flex-form mb-3">{{ field }}</div>
            </div>
          </div>
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-lg btn-primary mr-2">Create Issue</button>
    </form>
  </div>
</div>
{% endblock %}

anonticket/templates/anonticket/issue_pending.html
{% extends 'shared/layout.html' %}
{% load static %}
<!-- Load custom filters from shared app, including ISO 8901 Date-Time Converter -->
{% load custom_filters %}
<!-- Load markdownify -->
{% load markdownify %}
<!-- Extra links block for pages that have a user_identifier piped to them.-->
{% block extra_links %}
  {% include 'shared/extend_sidebar.html' %}
{% endblock %}
<!-- Start Page Render -->
{% block h3 %}
  </h3>
  <div class="row justify-content-between">
      <p class="col-auto mb-0 small pb-0 pt-0">{{issue.linked_project}}</p>
      <p class="col-auto text-muted small mb-0 pb-0 pt-0 text-right">Created by {{issue.linked_user.user_identifier}}</p>
  </div>
  <hr class="mb-0 mt-0">
  <div class="row justify-content-between">
    <div class="col-auto"><p class="mb-0 small pb-0 pt-0">Milestone: NA, Issue Pending Mod Approval.</p></div>
    <div class="col-auto">
      <p class="text-muted small mb-0 pb-0 pt-0 text-right">    
        Labels: NA, Issue Pending Mod Approval</p>
    </div>
  </div>
  <div class="row  mt-5">
    <div class="col-12">
      <h4><span class="badge badge-primary mr-2">Pending</span>{{issue.title|capfirst}}</h4>
    </div>
  <div class="col-12 small mt-0 mb-3 text-right">
  </div>
</div>
{% endblock %}
{% block subheader %} 
  <p class="small short-height">{{issue.description|capfirst|markdownify}}</p>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-12">
<!-- Generate a link to go back to the user's landing page -->
    {% url 'user-landing' issue.linked_user.user_identifier as go_back_url %}
    <p>
      <a href="{{go_back_url}}">Go Back To Landing Page</a>
    </p>
  </div>
</div>
{% endblock %}

anonticket/templates/anonticket/user_landing.html
<!-- Extend the layout template -->
<!-- Can leave any block as default if preferred -->
{% extends 'shared/layout.html' %}
<!-- Load static method for templates -->
{% load static %}
<!-- title block sets the main title on the page (in browser bar)-->
{% block title %}
  Anon Ticket
{% endblock %}
<!-- Extra links block for pages that have a user_identifier piped to them.-->
{% block extra_links %}
  {% include 'shared/extend_sidebar.html' %}
{% endblock %}
<!-- h3 block sets the main title -->
{% block h3 %}
  Anon Ticket
{% endblock %}

<!-- Subheader block sets the subheader -->
{% block subheader %} 
  User Landing Page for:
  <div class="p-2 pb-0">
    <h3 class="text-primary">{{results.user_identifier}}</h3>
  <!-- Check if user_found in results dictionary. If so, list actions already taken. -->
    {% if results.user_found %}
      <p class="small ml-0 mb-0">
        (***This User Identifier has been found. Feel free to bookmark this page to return to it at a later date.)
      </p>
    {% else %}
      <p class="small ml-0">
        (No actions taken yet with this user identifier. Feel free to bookmark this
        page to return to it at a later date.)
      </p>
    {% endif %}
  </div>
{% endblock %}
<!-- End of subheader block -->

<!-- Main content block  -->
{% block content %}
<div class="row">
  <div class="col-12">
    <!-- List actions that can be taken. -->
    <h4 class="mt-0">You can take the following actions:</h4>
    <!-- Generate the action URLS on the fly within the template. -->
    <p class='mt-4 mb-0'>
      <ul>
        <li>{% url 'project-list' results.user_identifier as project_list_url %}
          <a href="{{project_list_url}}">See a list all projects</a> that
          currently take ticket reports via Anon-Ticket. Each project 
          listed links to a detail page with a list of current issues.</li>
        <li>{% url 'issue-search' results.user_identifier as search_url %}
        <a href="{{search_url}}">Search for an issue</a> inside of a given project.</li>
        <li>{% url 'create-issue' results.user_identifier as create_url %}
        <a href="{{create_url}}">Create an issue</a> inside of a given project.</li>
        <li>To create a note on an existing issue, use one of the methods above 
          to navigate to an issue's detail page, and then click "Create Note."
        </li>
      </ul>
    </p>
  </div>
</div>

<!-- List the issues the user has created. -->
<div class="row">
  <div class="col-12 mt-3">
    <h4 class="mt-3">You have created the following issues:</h4>
    <p class="small short-height">
      (If you'd like to create a new issue, please use one of the options above.)
    </p> 
  </div>
</div>
<!-- If results.linked_issues, render the issues table. -->
{% if results.linked_issues %}
<div class="row">
  <div class="col-12 mt-3">
    <table>
      <thead>
        <th class="align-middle" style="width:15%">
          Project
        </th>
        <th class="align-middle">
          Issue # / Issue Title
        </th>
        <th class="align-middle" style="width:15%">
          Issue Status
        </th>
      </thead>
      <tbody>
        {% for issue in results.linked_issues %}
        <!-- If the issue has a gitlab.iid, it has been approved. -->
        {% if issue.gitlab_iid %}
        <tr>
          <td>
            {{issue.linked_project.name_with_namespace}}
          </td>
          <td>
            <!-- Generate issue-detail-view url -->
            {% url 'issue-detail-view' results.user_identifier issue.linked_project.slug issue.gitlab_iid as issue_url %}
            Issue #{{issue.gitlab_iid}}: <a href="{{issue_url}}">{{issue.title}}</a>
          </td>
          <td>
            {{ issue.get_reviewer_status_display }}
          </td>
        </tr>
        {% else %}
        <tr>
          <td>
            {{issue.linked_project.name_with_namespace}}
          </td>
          <td>
            <!-- Generated Pending Issue Detail View URL -->
            {% url 'pending-issue-detail-view' results.user_identifier issue.linked_project.slug issue.pk as issue_url %}
            Issue # (NA): <a href="{{issue_url}}">{{issue.title}}</a>
          </td>
          <td>
            {{ issue.get_reviewer_status_display }}
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<!-- Else, render the following block -->
{% else %}
<div class="row">
  <div class="col-12 mt-0">
    <p class="text-primary">You have not created any issues.</p>
  </div>
</div>
{% endif %}

<!-- List the notes the user has created. -->
<div class="row">
  <div class="col-12 mt-3">
    <h4 class="mt-4">You have created the following notes:</h4>
    <p class="small short-height">(To create a new note, <a href="{{search_url}}">
      search for the issue</a> you want to comment on, or look at the 
      <a href="{{project_list_url}}">project's detail view</a> to find it.) 
  </div>
</div>
<!-- If results.linked_notes, render the notes table. -->
{% if results.linked_notes %}
<div class="row">
  <div class="col-12 mt-3">
    <table>
      <thead>
        <th class="align-middle" style="width:15%">
          Project
        </th>
        <th class="align-middle">
          Issue # / Issue Title
        </th>
        <th class="align-middle">
          Note Excerpt and Link
        </th>
        <th class="align-middle" style="width:15%">
          Note Status
        </th>
      </thead>
      <tbody>
        {% for note in results.linked_notes %}
        <!-- If the note has a gitlab.id, it has been approved. Render approved notes. -->
        {% if note.gitlab_id %}
        <tr>
          <td>
            {{note.linked_project.short_name_with_namespace}}
          </td>
          <td>
            <!-- Generate a linke to the issue-detail-view url -->
            {% url 'issue-detail-view' results.user_identifier note.linked_project.slug note.issue_iid as issue_url %}
            Issue #{{note.issue_iid}}: 
            <a href="{{issue_url}}">{{note.gitlab_issue_title}}</a>
          </td>
          <td>
            {{note.body|capfirst|truncatewords:20}}
            <p class="mb-0 small"><a href="{{issue_url}}">(Posted to issue.)</a></p>
          </td>
          <td>
            {{ note.get_reviewer_status_display }}
          </td>
        </tr>
        <!-- If note has not been approved, render a slightly different row. -->
        {% else %}
        <tr>
          <td>
            {{note.linked_project.short_name_with_namespace}}
          </td>
          <td>
            <!-- Generated Pending Issue Detail View URL -->
            {% url 'issue-detail-view' results.user_identifier note.linked_project.slug note.issue_iid as issue_url %}
            Issue # {{note.issue_iid}}: <a href="{{issue_url}}">{{note.gitlab_issue_title}}</a>
          </td>
          <td>
            {% url 'pending-note' results.user_identifier note.linked_project.slug note.issue_iid note.pk as note_url %}
            {{ note.body|capfirst|truncatewords:20 }}
            <p class="mb-0 small"><a href="{{note_url}}">(See Full Note Text)</a></p>
          </td>
          <td>
            {{ note.get_reviewer_status_display }}
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<!-- Else, render the following block -->
{% else %}
<div class="row">
  <div class="col-12 mt-0">
    <p class="text-primary">You have not created any notes.</p>
  </div>
</div>
{% endif %}


{% endblock %}